from __future__ import annotations

from pathlib import Path
from typing import Any, List, Union

def read_csv(path: Union[str, Path]) -> Any: ...
def write_csv(df: Any, path: Union[str, Path]) -> None: ...
def write_parquet(df: Any, path: Union[str, Path]) -> None: ...
def discover_input_files(path_or_dir: Union[str, Path]) -> List[str]: ...
